In [1]:
'''
Movie Project Evaluation

Author: Diogo Gonçalves

Final project for Data analytics bootcamp @Ironhack Lisbon

December 2020
'''

'\nMovie Project Evaluation\n\nAuthor: Diogo Gonçalves\n\nFinal project for Data analytics bootcamp @Ironhack Lisbon\n\nDecember 2020\n'

In [1]:
#libraries used
import time
import pandas as pd
import pickle
import requests
from bs4 import BeautifulSoup
from scrapy import Selector
import threading
import multiprocessing
import csv
import regex as re

In [11]:
# getting and checking contents of IMDB datasets

# following this https://medium.com/analytics-vidhya/exploratory-data-analysis-imdb-dataset-cff0c3991ad5

# I downloaded all the tables in https://www.imdb.com/interfaces/ except the  “title.episode.tsv.gz” as 
# I am interested in movies in the notebook, not TV series.

# list file paths
path = 'Data/'
tsv_files = [path + 'name.basics.tsv.gz',
             path + 'title.akas.tsv.gz',
             path + 'title.basics.tsv.gz',
             path + 'title.crew.tsv.gz',
             path + 'title.principals.tsv.gz',
             path + 'title.ratings.tsv.gz']


# save all tables one by one into separate sav files (to save time loading them later)
for file in tsv_files:
     print(file)
     pickle.dump(pd.read_table(file,sep="\t",low_memory=False, na_values=["\\N","nan"]),
                 open(file[:-7]+".sav","wb"))

Data/name.basics.tsv.gz
Data/title.akas.tsv.gz
Data/title.basics.tsv.gz
Data/title.crew.tsv.gz
Data/title.principals.tsv.gz
Data/title.ratings.tsv.gz

In [2]:
path = 'Data/'
df_basics = pickle.load(open(path+"title.basics.sav","rb"))
df = df_basics[df_basics['titleType']=='movie']
df.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
8,tt0000009,movie,Miss Jerry,Miss Jerry,0,1894.0,NaN,45,Romance
331,tt0000335,movie,Soldiers of the Cross,Soldiers of the Cross,0,1900.0,NaN,NaN,"Biography,Drama"
498,tt0000502,movie,Bohemios,Bohemios,0,1905.0,NaN,100,NaN
570,tt0000574,movie,The Story of the Kelly Gang,The Story of the Kelly Gang,0,1906.0,NaN,70,"Biography,Crime,Drama"
610,tt0000615,movie,Robbery Under Arms,Robbery Under Arms,0,1907.0,NaN,NaN,Drama

In [3]:
# I'll try to get the 1)financial data and 2)synopsis from each movie page, that way i won't have so many problems 
# matching titles as if I scrapped the info form some other website

# let's try with a single page
url = 'https://www.imdb.com/title/tt0082971/'
request = requests.get(url)
html = request.content
soup = BeautifulSoup(html)
soup

<!DOCTYPE html>
<html xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:og="http://ogp.me/ns#">
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="app-id=342792525, app-argument=imdb:///title/tt0082971?src=mdot" name="apple-itunes-app"/>
<script type="text/javascript">var IMDbTimer={starttime: new Date().getTime(),pt:'java'};</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadTitle", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_title"] = new Date().getTime(); })(IMDbTimer);</script>
<title>Os Salteadores da Arca Perdida (1981) - IMDb</title>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_title"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadTitle", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadTitle", {wb: 1});
    }
</script>
<link href="https://www.imdb.com/title/tt0082971/" rel="canonical"/>
<meta content="http://www.imdb.com/title/tt0082971/" property="og:url"/>
<link href="https://m.imdb.com/title/tt0082971/" media="only screen and (max-width: 640px)" rel="alternate"/>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadIcons", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_icon"] = new Date().getTime(); })(IMDbTimer);</script>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_desktop_32x32._CB1582158068_.png" rel="icon" sizes="32x32"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_iPad_retina_167x167._CB1582158068_.png" rel="icon" sizes="167x167"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/favicon_iPhone_retina_180x180._CB1582158069_.png" rel="icon" sizes="180x180"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile._CB479963088_.png" rel="apple-touch-icon"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile-76x76._CB479962152_.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-mobile-120x120._CB479963088_.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/apple-touch-icon-web-152x152._CB479963088_.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images-ANDW73HA/android-mobile-196x196._CB479962153_.png" rel="shortcut icon" sizes="196x196"/>
<meta content="#000000" name="theme-color"/>
<link href="https://m.media-amazon.com/images/G/01/imdb/images/imdbsearch-3349468880._CB466670431_.xml" rel="search" title="IMDb" type="application/opensearchdescription+xml"/>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_icon"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadIcons", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadIcons", {wb: 1});
    }
</script>
<meta content="tt0082971" property="pageId"/>
<meta content="title" property="pageType"/>
<meta content="main" property="subpageType"/>
<link href="https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_UY1200_CR84,0,630,1200_AL_.jpg" rel="image_src"/>
<meta content="https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_UY1200_CR84,0,630,1200_AL_.jpg" property="og:image"/>
<meta content="video.movie" property="og:type"/>
<meta content="115109575169727" property="fb:app_id"/>
<meta content="Raiders of the Lost Ark (1981) - IMDb" property="og:title"/>
<meta content="IMDb" property="og:site_name"/>
<meta content="Os Salteadores da Arca Perdida (1981) - IMDb" name="title"/>
<meta content="Directed by Steven Spielberg.  With Harrison Ford, Karen Allen, Paul Freeman, John Rhys-Davies. In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its awesome powers." name="description"/>
<meta content="Directed by Steven Spielberg.  With Harrison Ford, Karen Allen, Paul Freeman, John Rhys-Davies. In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its awesome powers." property="og:description"/>
<meta content="Reviews, Showtimes, DVDs, Photos, Message Boards, User Ratings, Synopsis, Trailers, Credits" name="keywords"/>
<meta content="KH77TY5SDRAJ3G8RFEAH" name="request_id"/>
<script type="application/ld+json">{
  "@context": "http://schema.org",
  "@type": "Movie",
  "url": "/title/tt0082971/",
  "name": "Raiders of the Lost Ark",
  "image": "https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_.jpg",
  "genre": [
    "Action",
    "Adventure"
  ],
  "contentRating": "PG",
  "actor": [
    {
      "@type": "Person",
      "url": "/name/nm0000148/",
      "name": "Harrison Ford"
    },
    {
      "@type": "Person",
      "url": "/name/nm0000261/",
      "name": "Karen Allen"
    },
    {
      "@type": "Person",
      "url": "/name/nm0293550/",
      "name": "Paul Freeman"
    },
    {
      "@type": "Person",
      "url": "/name/nm0722636/",
      "name": "John Rhys-Davies"
    }
  ],
  "director": {
    "@type": "Person",
    "url": "/name/nm0000229/",
    "name": "Steven Spielberg"
  },
  "creator": [
    {
      "@type": "Person",
      "url": "/name/nm0001410/",
      "name": "Lawrence Kasdan"
    },
    {
      "@type": "Person",
      "url": "/name/nm0000184/",
      "name": "George Lucas"
    },
    {
      "@type": "Person",
      "url": "/name/nm0442241/",
      "name": "Philip Kaufman"
    },
    {
      "@type": "Organization",
      "url": "/company/co0023400/"
    },
    {
      "@type": "Organization",
      "url": "/company/co0071326/"
    }
  ],
  "description": "Raiders of the Lost Ark is a movie starring Harrison Ford, Karen Allen, and Paul Freeman. In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler\u0027s...",
  "datePublished": "1981-06-12",
  "keywords": "nazi,ark of the covenant,indiana jones,archeologist,famous opening scene",
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingCount": 875748,
    "bestRating": "10.0",
    "worstRating": "1.0",
    "ratingValue": "8.4"
  },
  "review": {
    "@type": "Review",
    "itemReviewed": {
      "@type": "CreativeWork",
      "url": "/title/tt0082971/"
    },
    "author": {
      "@type": "Person",
      "name": "ma-cortes"
    },
    "dateCreated": "2005-08-15",
    "inLanguage": "English",
    "name": "Magnificent action-packed adventure film that spawned two sequels and numerous copies",
    "reviewBody": "It\u0027s the first part of adventures trilogy , going on the way of the 30s classic films and the Comics-Books language. The picture blends comedy,adventures action,rip roaring,cliff hunger,tongue-in-cheek and is extremely entertaining and fun . The archaeologist Indiana Jones with his bull whip-wielding and hat will confront dastard Nazis (Ronald Lacey) in Peru, Nepal and Egypt to the obtaining the Moiseh ark with the Covenant\u0027s tables . He\u0027s only helped by two feisty adventurers (Karen Allen and John Rhys Davies) . Indy fights nasty Arabs , decodes hieroglyphics and faces off hundreds of snakes . The movie attempts to go on the path from great classics during the 30-40s and the comic-books narrative along with the special characteristics of the terror cinema of 80 decade.\n\nDr.Indiana executes feats of derring-do in various exotics countries. The action highlights include the opening sequence in a Peruvian jungle temple and the creepy and spooky final, but some scenes aren\u0027t for squeamish kids . It\u0027s realized in James Bond style and high-adventure and it is driven with enormous , formidable fair-play . This breathtaking movie has a number of scenes that will have you on the edge of your seat, but the action never lets up . The enjoyable screenplay was wonderfully written by George Lucas (film\u0027s producer) , Philip Kauffman and Lawrence Kasdan . In the picture there\u0027re several exotic locations , cliff-hangers, tongue-in-cheek , daring escapes , rip-roaring , derring-do , it is a very bemusing cinematic roller-coaster ride . It\u0027s a throw-back to old-fashioned Technicolor amusement with hints of serial with thousands of dollars in budget .\n\nHarrison Ford interprets masterfully the daredevil and brave archaeologist transformed into an action man . Karen Allen plays his untameable and impulsive couple who\u0027ll have a little romance with Indy . The movie has great loads of action , special effects galore and the habitual and excellent , as always , John Williams musical core . Dazzling action set-pieces are stunningly mounted by Steven Spielberg . The film has entered the lists of ten most popular of all time . It is followed by ¨Indiana Jones and the Temple of Doom¨ and¨ The last Crusade¨. And by the TV series ,also produced by George Lucas : ¨The young Indiana Jones¨with Sean Patrick Flannery .It\u0027s a must see for the adventures fans . Rating : Awesome.",
    "reviewRating": {
      "@type": "Rating",
      "worstRating": "1",
      "bestRating": "10",
      "ratingValue": "8"
    }
  },
  "duration": "PT1H55M",
  "trailer": {
    "@type": "VideoObject",
    "name": "Official HD Trailer",
    "embedUrl": "/video/imdb/vi3747396377",
    "thumbnail": {
      "@type": "ImageObject",
      "contentUrl": "https://m.media-amazon.com/images/M/MV5BOGFhNTAyYjMtNGJlNi00NWFmLTllNTgtYzdhZjE5NmU4MTQ4XkEyXkFqcGdeQXJoYW5uYWg@._V1_.jpg"
    },
    "thumbnailUrl": "https://m.media-amazon.com/images/M/MV5BOGFhNTAyYjMtNGJlNi00NWFmLTllNTgtYzdhZjE5NmU4MTQ4XkEyXkFqcGdeQXJoYW5uYWg@._V1_.jpg",
    "uploadDate": "2018-09-14T22:27:11Z"
  }
}</script>
<script>
        (function (win) {
            win.PLAID_LOAD_FONTS_FIRED = true;

            if (typeof win.FontFace !== "undefined"
                && typeof win.Promise !== "undefined") {
                if (win.ue) {
                    win.uet("bb", "LoadRoboto", { wb: 1 });
                }
                var allowableLoadTime = 1000;
                var startTimeInt = +new Date();
                var roboto = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3Rv.woff2)',
                    { style:'normal', weight: 400 });
                var robotoMedium = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3RvTWVk.woff2)',
                    { style:'normal', weight: 500 });
                var robotoBold = new FontFace('Roboto',
                    'url(https://m.media-amazon.com/images/G/01/IMDb/cm9ib3RvQm9sZA.woff2)',
                    { style:'normal', weight: 600 });
                var robotoLoaded = roboto.load();
                var robotoMediumLoaded = robotoMedium.load();
                var robotoBoldLoaded = robotoBold.load();

                win.Promise.all([robotoLoaded, robotoMediumLoaded, robotoBoldLoaded]).then(function() {
                    var loadTimeInt = +new Date();
                    var robotoLoadedCount = 0;
                    if ((loadTimeInt - startTimeInt) <= allowableLoadTime) {
                        win.document.fonts.add(roboto);
                        win.document.fonts.add(robotoMedium);
                        win.document.fonts.add(robotoBold);
                        robotoLoadedCount++;
                    }
                    if (win.ue) {
                        win.ue.count("roboto-loaded", robotoLoadedCount);
                        win.uet("be", "LoadRoboto", { wb: 1 });
                        win.uex("ld", "LoadRoboto", { wb: 1 });
                    }
                }).catch(function() {
                    if (win.ue) {
                        win.ue.count("roboto-loaded", 0);
                    }
                });
            } else {
                if (win.ue) {
                    win.ue.count("roboto-load-not-attempted", 1);
                }
            }
        })(window);
    </script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadCSS", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_css"] = new Date().getTime(); })(IMDbTimer);</script>
<link href="https://m.media-amazon.com/images/I/41efLTT40QL.css" rel="stylesheet" type="text/css"/><link href="https://m.media-amazon.com/images/I/41hSeqiObCL.css" rel="stylesheet" type="text/css"/>
<!-- h=ics-c52xl-15-1f-96eb22e6.us-east-1 -->
<link href="https://m.media-amazon.com/images/G/01/imdb/css/collections/title-flat-v2-615412840._CB414882882_.css" rel="stylesheet" type="text/css"/>
<noscript>
<link href="https://m.media-amazon.com/images/G/01/imdb/css/wheel/nojs-2827156349._CB468153063_.css" rel="stylesheet" type="text/css"/>
</noscript>
<script>(function(t){ (t.events = t.events || {})["csm_head_post_css"] = new Date().getTime(); })(IMDbTimer);</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadCSS", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadCSS", {wb: 1});
    }
</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadJS", {wb: 1});
    }
</script>
<script>
    if (typeof uet == 'function') {
      uet("bb", "LoadHeaderJS", {wb: 1});
    }
</script>
<script>(function(t){ (t.events = t.events || {})["csm_head_pre_ads"] = new Date().getTime(); })(IMDbTimer);</script>
<script type="text/javascript">
            // ensures js doesn't die if ads service fails.
            // Note that we need to define the js here, since ad js is being rendered inline after this.
            (function(f) {
                // Fallback javascript, when the ad Service call fails.

                if((window.csm == null || window.generic == null || window.consoleLog == null)) {
                    if (window.console && console.log) {
                        console.log("one or more of window.csm, window.generic or window.consoleLog has been stubbed...");
                    }
                }

                window.csm = window.csm || { measure:f, record:f, duration:f, listen:f, metrics:{} };
                window.generic = window.generic || { monitoring: { start_timing: f, stop_timing: f } };
                window.consoleLog = window.consoleLog || f;
            })(function() {});
        </script>
<script type="text/javascript">
    if (!window.RadWidget) {
        window.RadWidget = {
            registerReactWidgetInstance: function(input) {
                window.RadWidget[input.widgetName] = window.RadWidget[input.widgetName] || [];
                window.RadWidget[input.widgetName].push({
                    id: input.instanceId,
                    props: JSON.stringify(input.model)
                })
            },
            getReactWidgetInstances: function(widgetName) {
                return window.RadWidget[widgetName] || []
            }
        };
    }
</script> <script>
    if ('csm' in window) {
      csm.measure('csm_head_delivery_finished');
    }
  </script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadHeaderJS", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadHeaderJS", {wb: 1});
    }
</script>
<script>
    if (typeof uet == 'function') {
      uet("be", "LoadJS", {wb: 1});
    }
</script>
<script>
    if (typeof uex == 'function') {
      uex("ld", "LoadJS", {wb: 1});
    }
</script>
</head>
<body class="fixed" id="styleguide-v2">
<script>
    if (typeof uet == 'function') {
      uet("bb");
    }
</script>
<script>
    if ('csm' in window) {
      csm.measure('csm_body_delivery_started');
    }
  </script>
<script>
    if (typeof uet == 'function') {
      uet("ns");
    }
</script>
<style data-styled="gwOpQB iwkRT erYeKd bkeTFm diDBNJ eWjUDO LrpYY dzfmPm dFDExU RQLCk YOYgO ddqdtC hOXnzb cIKARP gTFTwO dKTgZt crQfrC OQYVG hjoCyi hoAGyu cECatH kaVyhF eIWOUD" data-styled-version="4.3.2">
/* sc-component-id: NavLogo-e02kni-0 */
.ddqdtC{-webkit-flex-shrink:0;-ms-flex-negative:0;flex-shrink:0;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none;margin-left:0.25rem;margin-right:auto;-webkit-order:1;-ms-flex-order:1;order:1;position:relative;} @media screen and (min-width:1024px){.ddqdtC{margin-left:auto;margin-right:0.5rem;-webkit-order:0;-ms-flex-order:0;order:0;padding-left:0;}} @media (hover:hover) and (pointer:fine){.ddqdtC:focus{outline:1px dashed currentColor;}.ddqdtC:focus:active{outline:0;}.ddqdtC:before,.ddqdtC:after{border-radius:10%;bottom:0;content:'';height:100%;left:0;margin:auto;opacity:0;position:absolute;right:0;top:0;-webkit-transition:opacity .2s cubic-bezier(1,1,1,1);transition:opacity .2s cubic-bezier(1,1,1,1);width:100%;}}
/* sc-component-id: SearchTypeahead-sc-112a48v-0 */
.OQYVG li:first-child > ._3CzPBqlWRmSAoWxtvQQ5Eo{border-top:none;}
/* sc-component-id: FlyoutMenu-xq6xx0-0 */
.crQfrC{position:relative;} .crQfrC.navbar__flyout__text-button-after-mobile,.crQfrC .navbar__flyout__text-button-after-mobile{display:none;} .crQfrC .navbar__flyout__text-button-after-mobile > div{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;} .crQfrC .navbar__flyout--menu{top:100%;position:absolute;margin-top:.25rem;} .crQfrC.crQfrC.navbar__flyout--positionLeft .navbar__flyout--menu{left:0;right:auto;} @media screen and (min-width:600px){.crQfrC.navbar__flyout--breakpoint-m .navbar__flyout__icon-on-mobile{display:none;}.crQfrC.navbar__flyout--breakpoint-m .navbar__flyout__text-button-after-mobile{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;}} @media screen and (min-width:1024px){.crQfrC.navbar__flyout--breakpoint-l .navbar__flyout__icon-on-mobile{display:none;}.crQfrC.navbar__flyout--breakpoint-l .navbar__flyout__text-button-after-mobile{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;}} @media screen and (min-width:1280px){.crQfrC.navbar__flyout--breakpoint-xl .navbar__flyout__icon-on-mobile{display:none;}.crQfrC.navbar__flyout--breakpoint-xl .navbar__flyout__text-button-after-mobile{display:-webkit-inline-box;display:-webkit-inline-flex;display:-ms-inline-flexbox;display:inline-flex;}} .crQfrC .navbar__flyout__button-pointer{-webkit-transition:-webkit-transform 0.2s;-webkit-transition:transform 0.2s;transition:transform 0.2s;-webkit-transform:rotateX(0);-ms-transform:rotateX(0);transform:rotateX(0);} .crQfrC.navbar__flyout--isVisible .navbar__flyout__button-pointer{-webkit-transform:rotateX(180deg);-ms-transform:rotateX(180deg);transform:rotateX(180deg);}
/* sc-component-id: SearchCategorySelector__StyledContainer-sc-18f40f7-0 */
.dKTgZt .search-category-selector__opener{border-radius:2px 0 0 2px;padding:0 0 0 0.5rem;min-height:32px;height:20px;border-right:1px solid rgba(0,0,0,0.3);} .dKTgZt _1L5qcXA4wOKR8LeHJgsqja{cursor:pointer;}
/* sc-component-id: SearchForm-dxsip9-0 */

In [4]:
# saving the storyline
story = soup.find('div',{'class':'inline canwrap'}).find('span').get_text().strip()
story

'The year is 1936. An archeology professor named Indiana Jones is venturing in the jungles of South America searching for a golden statue. Unfortunately, he sets off a deadly trap but miraculously escapes. Then, Jones hears from a museum curator named Marcus Brody about a biblical artifact called The Ark of the Covenant, which can hold the key to humanly existence. Jones has to venture to vast places such as Nepal and Egypt to find this artifact. However, he will have to fight his enemy Rene Belloq and a band of Nazis in order to reach it.'

In [5]:
# saving the budget and cumulative worldwide gross
#titleDetails = soup.find('div',{'id':'titleDetails'})
#titleDetails.find_all('div', class_='txt-block')

#res = requests.get(url)
res = request
sel = Selector(res)
budget = ' '.join(sel.css(".txt-block:contains('Budget')::text").extract()).strip()
gross = ' '.join(sel.css(".txt-block:contains('Gross USA')::text").extract()).strip()
cumulative = ' '.join(sel.css(".txt-block:contains('Cumulative Worldwide')::text").extract()).strip()
print(f'budget: {budget}\ngross: {gross}\ncumulative: {cumulative}')

budget: $18,000,000
gross: $248,159,971
cumulative: $389,925,971

In [3]:
# ok, it's time to get my ip banned

# I'll start by reducing the scope to only movies made since 1980, if that goes fast I'll try to get older info
df80 = df[df['startYear'] > 1979]

In [4]:
# turns out scrapping 330k movies takes some days using my current method. I need to make the list shorter
# let's drop rows without 'runtimeMinutes'
df80 = df80.dropna(subset=['runtimeMinutes']) #this drops aroun 78k rows, nice

# let's drop all movies less than 70 min long
df80['runtimeMinutes'] = df80['runtimeMinutes'].astype(int)
df80 = df80[df80['runtimeMinutes']>=70] #this step removes an additional 50k

In [5]:
# I want to create a list of all IMDB movies URLs (I plan to scrape some additional inofrmation later)
prefix = 'https://www.imdb.com/title/'
movies_url = [prefix + idcon for idcon in df80['tconst']]
movies_url[0]

'https://www.imdb.com/title/tt0015724'

In [142]:
def get_details(movies_url):
    '''
    For a given list of IMDB movies URLs returns list containing the URL, Storyline, 
    Budget, Gross USA, Cumulative Worldwide Gross
    '''
    #start = time.perf_counter()
    story = []
    budget = []
    gross = []
    cumulative = []

    for url in movies_url:
        print(url)
        request = requests.get(url)
        html = request.content
        soup = BeautifulSoup(html)
        try:
#            story.append(soup.find('div',{'class':'inline canwrap'}).find('span').get_text().strip())
            story = soup.find('div',{'class':'inline canwrap'}).find('span').get_text().strip()
        except:
            pass
        res = request
        sel = Selector(res)
        try:
#            budget.append(' '.join(sel.css(".txt-block:contains('Budget')::text").extract()).strip())
            budget = ' '.join(sel.css(".txt-block:contains('Budget')::text").extract()).strip()
        except:
            pass
        try:
#            gross.append(' '.join(sel.css(".txt-block:contains('Gross USA')::text").extract()).strip())
            gross = ' '.join(sel.css(".txt-block:contains('Gross USA')::text").extract()).strip()
        except:
            pass
        try:
#            cumulative.append(' '.join(sel.css(".txt-block:contains('Cumulative Worldwide')::text").extract()).strip())
            cumulative = ' '.join(sel.css(".txt-block:contains('Cumulative Worldwide')::text").extract()).strip()

        except:
            pass
        try:
            rating = soup.find("div",{'class':'subtext'}).contents[0].string.strip()        
        except:
            pass
        row = [url,story,budget,gross,cumulative,rating]
#        with csv_writer_lock:
        with open("movie_details.csv", mode="a") as f1:
            details_writer = csv.writer(f1, delimiter=",")
            details_writer.writerow(row)
    return row

    #details = pd.DataFrame()
    #details['url'] = movies_url
    #details['story'] = story
    #details['budget'] = budget
    #details['gross'] = gross
    #details['cumulative'] = cumulative
    #finish = time.perf_counter()
    #print('finished in '+str(finish-start)+' seconds')
    #return details

#csv_writer_lock = threading.Lock()
#details = get_details(movies_url[:20])

get_details(['https://www.imdb.com/title/tt0097576/'])

https://www.imdb.com/title/tt0097576/

['https://www.imdb.com/title/tt0097576/',
 'An art collector appeals to Indiana Jones to embark on a search for the Holy Grail. He learns that another archaeologist has disappeared while searching for the precious goblet, and the missing man is his own father, Dr. Henry Jones. The artifact is much harder to find than they expected, and its powers are too much for those impure of heart.',
 '$48,000,000',
 '$197,171,806',
 '$474,171,806',
 'M/12']

In [6]:
 len(movies_url)

203148

In [14]:
type (movies_url[0])

str

In [16]:
# doing this without paralelization makes the task take too long. I would need more than a week to scrape
# I started by restricting the movies that get into my movies_url list
# I may need to go further, and select only us made movies, or reduce the timeframe 
# I can't get pararelization to work on jupyter, I'll do it in google collab
# I need to export the list of movies to scrape
with open('movies_url.pkl', 'wb') as f:
    pickle.dump(movies_url, f)

In [ ]:
'''
!!! END OF SCRAPPING !!!
'''

In [2]:
# I will now import the result of the scraping done in g. collab
# the scrapping takes around 8 hours, I may include data for aditional decades later
dfs = pd.read_csv('Data/movie_details.csv', names=['url','story','budget','gross','cumulative','rating'])
dfs.head()

,url,story,budget,gross,cumulative,rating
0,https://www.imdb.com/title/tt0080933,A biological experiment in Florida goes awry. ...,"$3,500,000",NaN,NaN,Not Rated
1,https://www.imdb.com/title/tt0080803,A large quantity of gold is stolen from the go...,NaN,NaN,NaN,NaN
2,https://www.imdb.com/title/tt0080522,NaN,NaN,NaN,NaN,NaN
3,https://www.imdb.com/title/tt0078202,NaN,NaN,NaN,NaN,NaN
4,https://www.imdb.com/title/tt0015724,NaN,NaN,NaN,NaN,NaN

In [3]:
dfs.shape

(204148, 6)

In [4]:
dfs.dropna().shape

(8093, 6)

In [5]:
# For now I'll drop any row with missing values
dfs.dropna(inplace = True)

dfs.head()

,url,story,budget,gross,cumulative,rating
5,https://www.imdb.com/title/tt0080661,"While taking a shower, Kate Miller, a middle-a...","$6,500,000","$31,899,000","$31,899,000",R
14,https://www.imdb.com/title/tt0080934,"In New York City, journalist Blair Maynard con...","$22,000,000","$15,716,828","$15,716,828",R
27,https://www.imdb.com/title/tt0035423,Kate and her actor brother live in N.Y. in the...,"$48,000,000","$47,121,859","$76,019,048",PG-13
34,https://www.imdb.com/title/tt0081249,An unknown terrorist has developed a new type ...,"$15,000,000","$14,662,035","$14,662,035",PG
35,https://www.imdb.com/title/tt0079285,Two lovers stationed at a remote base in the a...,"GBP10,000,000","$9,000,000","$9,000,000",R

In [6]:
print(dfs.shape)
print(dfs.drop_duplicates(subset=['url']).shape)

(8093, 6)
(8044, 6)

In [7]:
# remove rows with duplicate ids
dfs.drop_duplicates(subset=['url'],inplace=True)

In [8]:
# get id from url to be able to merge with the downloaded datasets later
def get_id(row):
    '''
    strips the last 9 chars of row['url'] to return the ID
    '''
    return str(row['url'])[-9:]

dfs['id'] = dfs.apply(lambda row: get_id(row), axis = 1)
dfs.head()

,url,story,budget,gross,cumulative,rating,id
5,https://www.imdb.com/title/tt0080661,"While taking a shower, Kate Miller, a middle-a...","$6,500,000","$31,899,000","$31,899,000",R,tt0080661
14,https://www.imdb.com/title/tt0080934,"In New York City, journalist Blair Maynard con...","$22,000,000","$15,716,828","$15,716,828",R,tt0080934
27,https://www.imdb.com/title/tt0035423,Kate and her actor brother live in N.Y. in the...,"$48,000,000","$47,121,859","$76,019,048",PG-13,tt0035423
34,https://www.imdb.com/title/tt0081249,An unknown terrorist has developed a new type ...,"$15,000,000","$14,662,035","$14,662,035",PG,tt0081249
35,https://www.imdb.com/title/tt0079285,Two lovers stationed at a remote base in the a...,"GBP10,000,000","$9,000,000","$9,000,000",R,tt0079285

In [9]:
# I'll drop url, it's redundant now
dfs.drop(columns=['url'], inplace = True)
dfs.head()

,story,budget,gross,cumulative,rating,id
5,"While taking a shower, Kate Miller, a middle-a...","$6,500,000","$31,899,000","$31,899,000",R,tt0080661
14,"In New York City, journalist Blair Maynard con...","$22,000,000","$15,716,828","$15,716,828",R,tt0080934
27,Kate and her actor brother live in N.Y. in the...,"$48,000,000","$47,121,859","$76,019,048",PG-13,tt0035423
34,An unknown terrorist has developed a new type ...,"$15,000,000","$14,662,035","$14,662,035",PG,tt0081249
35,Two lovers stationed at a remote base in the a...,"GBP10,000,000","$9,000,000","$9,000,000",R,tt0079285

In [10]:
# get the currency of the budget and cumulative gross before cleaning string 
def get_currency(row, column):
    '''
    returns the currency in a given column
    '''
    if str(row[column])[0] == '$':
        return 'USD'
    else:
        return str(row[column])[:3]

dfs['budget_cy'] = dfs.apply(lambda row: get_currency(row,'budget'), axis = 1)
dfs['gross_cy'] = dfs.apply(lambda row: get_currency(row,'gross'), axis = 1)
dfs['cumulative_cy'] = dfs.apply(lambda row: get_currency(row,'cumulative'), axis = 1)
dfs.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy
5,"While taking a shower, Kate Miller, a middle-a...","$6,500,000","$31,899,000","$31,899,000",R,tt0080661,USD,USD,USD
14,"In New York City, journalist Blair Maynard con...","$22,000,000","$15,716,828","$15,716,828",R,tt0080934,USD,USD,USD
27,Kate and her actor brother live in N.Y. in the...,"$48,000,000","$47,121,859","$76,019,048",PG-13,tt0035423,USD,USD,USD
34,An unknown terrorist has developed a new type ...,"$15,000,000","$14,662,035","$14,662,035",PG,tt0081249,USD,USD,USD
35,Two lovers stationed at a remote base in the a...,"GBP10,000,000","$9,000,000","$9,000,000",R,tt0079285,GBP,USD,USD

In [11]:
dfs = dfs[dfs['id']!='tt0107492'] # Iknow this row has text on the budget column for some reason, I have to drop it

In [12]:
# now I'll clean the strings in budget and cumulative to get the numbers

def get_number(row, column):
        try:
            return int(re.sub("[^0-9]", "", str(row[column])))
        except:
            print(row['id'])
dfs['budget'] = dfs.apply(lambda row: get_number(row,'budget'), axis = 1)
dfs['gross'] = dfs.apply(lambda row: get_number(row,'gross'), axis = 1)
dfs['cumulative'] = dfs.apply(lambda row: get_number(row,'cumulative'), axis = 1)
dfs.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy
5,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD
14,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD
27,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD
34,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD
35,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD

In [13]:
dfs.dtypes

story            object
budget            int64
gross             int64
cumulative        int64
rating           object
id               object
budget_cy        object
gross_cy         object
cumulative_cy    object
dtype: object

In [14]:
# Besides deciding if to convert budget_cy to USD or just dropping rows with different currencies, 
# I have to decide if I want to use gross us or not. When I have the full dataset it will be easier to decide
dfs.groupby('budget_cy').count()

,story,budget,gross,cumulative,rating,id,gross_cy,cumulative_cy
budget_cy,,,,,,,,
ARS,2,2,2,2,2,2,2,2
ATS,1,1,1,1,1,1,1,1
AUD,33,33,33,33,33,33,33,33
BEF,1,1,1,1,1,1,1,1
BRL,10,10,10,10,10,10,10,10
Bud,1,1,1,1,1,1,1,1
CAD,74,74,74,74,74,74,74,74
CHF,2,2,2,2,2,2,2,2
CLP,1,1,1,1,1,1,1,1
CNY,12,12,12,12,12,12,12,12
CZK,3,3,3,3,3,3,3,3
DEM,12,12,12,12,12,12,12,12
DKK,8,8,8,8,8,8,8,8
DOP,1,1,1,1,1,1,1,1
Dri,1,1,1,1,1,1,1,1
ESP,6,6,6,6,6,6,6,6
EUR,298,298,298,298,298,298,298,298
FIM,1,1,1,1,1,1,1,1
FRF,24,24,24,24,24,24,24,24
GBP,117,117,117,117,117,117,117,117
HKD,8,8,8,8,8,8,8,8
HUF,5,5,5,5,5,5,5,5
IEP,1,1,1,1,1,1,1,1
INR,84,84,84,84,84,84,84,84
ISK,1,1,1,1,1,1,1,1
ITL,1,1,1,1,1,1,1,1
JPY,13,13,13,13,13,13,13,13
KRW,10,10,10,10,10,10,10,10
MXN,5,5,5,5,5,5,5,5
NGN,1,1,1,1,1,1,1,1
NOK,14,14,14,14,14,14,14,14
NZD,1,1,1,1,1,1,1,1
PLN,1,1,1,1,1,1,1,1
Pro,1,1,1,1,1,1,1,1
RUR,1,1,1,1,1,1,1,1
SEK,9,9,9,9,9,9,9,9
SGD,2,2,2,2,2,2,2,2
THB,3,3,3,3,3,3,3,3
USD,7272,7272,7272,7272,7272,7272,7272,7272
VEB,1,1,1,1,1,1,1,1
ZAR,1,1,1,1,1,1,1,1

In [15]:
# let's start to create the final table(s)
# I think I need at least two tables, one with the movie data, and other for actors
# for now, I'll work on the movie data one

In [16]:
# let's merge and create the main movies dataframe

In [17]:
# merging with title.basics
path='Data/'
movies = pd.merge(dfs,pickle.load(open(path+"title.basics.sav","rb")),left_on='id',right_on='tconst')
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,tt0080661,movie,Dressed to Kill,Dressed to Kill,0,1980.0,NaN,104,"Crime,Drama,Mystery"
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,tt0080934,movie,The Island,The Island,0,1980.0,NaN,109,"Action,Adventure,Drama"
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,tt0035423,movie,Kate & Leopold,Kate & Leopold,0,2001.0,NaN,118,"Comedy,Fantasy,Romance"
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,tt0081249,movie,The Nude Bomb,The Nude Bomb,0,1980.0,NaN,94,"Action,Comedy,Crime"
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,tt0079285,movie,Saturn 3,Saturn 3,0,1980.0,NaN,96,"Adventure,Horror,Sci-Fi"

In [18]:
movies.shape

(8031, 18)

In [19]:
print(movies.shape)
print(movies.drop_duplicates(subset=['id']).shape)

(8031, 18)
(8031, 18)

In [20]:
movies.drop(columns=['endYear','originalTitle','titleType','tconst','isAdult'], inplace = True)
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery"
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama"
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance"
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime"
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi"

In [21]:
movies = pd.merge(movies,pickle.load(open(path+"title.ratings.sav","rb")),left_on='id',right_on='tconst')
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,tconst,averageRating,numVotes
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",tt0080661,7.1,34936
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",tt0080934,5.3,3789
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",tt0035423,6.4,78453
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",tt0081249,5.2,2988
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",tt0079285,5.2,8291

In [22]:
movies.drop(columns=['tconst'], inplace = True)

In [23]:
movies = pd.merge(movies,pickle.load(open(path+"title.crew.sav","rb")),left_on='id',right_on='tconst')
movies.shape

(8030, 18)

In [24]:
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,tconst,directors,writers
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",7.1,34936,tt0080661,nm0000361,nm0000361
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",5.3,3789,tt0080934,nm0006916,nm0001940
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",6.4,78453,tt0035423,nm0003506,"nm0737216,nm0003506"
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",5.2,2988,tt0081249,nm0232795,"nm0000316,nm0377750,nm0838441,nm0199049,nm0827767"
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",5.2,8291,tt0079285,"nm0058045,nm0002045","nm0025007,nm0058045"

In [25]:
movies.drop(columns=['writers','tconst'], inplace = True)
movies.shape

(8030, 16)

In [26]:
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,directors
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",7.1,34936,nm0000361
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",5.3,3789,nm0006916
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",6.4,78453,nm0003506
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",5.2,2988,nm0232795
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",5.2,8291,"nm0058045,nm0002045"

In [27]:
principals = pickle.load(open(path+"title.principals.sav","rb"))

In [28]:
principals[principals['tconst']=='tt0076759']

,tconst,ordering,nconst,category,job,characters
647896,tt0076759,10,nm0156816,editor,film editor,NaN
647897,tt0076759,1,nm0000434,actor,NaN,"[""Luke Skywalker""]"
647898,tt0076759,2,nm0000148,actor,NaN,"[""Han Solo""]"
647899,tt0076759,3,nm0000402,actress,NaN,"[""Princess Leia Organa""]"
647900,tt0076759,4,nm0000027,actor,NaN,"[""Ben Obi-Wan Kenobi""]"
647901,tt0076759,5,nm0000184,director,NaN,NaN
647902,tt0076759,6,nm0476030,producer,producer,NaN
647903,tt0076759,7,nm0564768,producer,producer,NaN
647904,tt0076759,8,nm0002354,composer,NaN,NaN
647905,tt0076759,9,nm0852405,cinematographer,director of photography,NaN

In [29]:
#let's select only top 3 billed, and drop the rest
principals = principals[(principals['ordering']<=3)&((principals['category']=='actor')|(principals['category']=='actress'))]
principals.head()

       tconst  ordering     nconst category  job        characters
11  tt0000005         1  nm0443482    actor  NaN    ["Blacksmith"]
12  tt0000005         2  nm0653042    actor  NaN     ["Assistant"]
16  tt0000007         1  nm0179163    actor  NaN               NaN
17  tt0000007         2  nm0183947    actor  NaN               NaN
21  tt0000008         1  nm0653028    actor  NaN  ["Sneezing Man"]

In [30]:
#let's build a pivot table where the index is tconst, columns are category, and values are nconst 
# agreggated by concat or sum, or better yet with a function that puts a comma in between

def commatose(array):
    '''
    takes an array of strings and returns a string split by comma
    '''
    s = ""
    for i in array:
        if s != '':
            s = s + ',' + i
        else:
            s = i
    return s

principals = pd.pivot_table(principals, values = 'nconst', index = 'tconst', aggfunc = commatose)
principals.head()

                                  nconst
tconst
tt0000005            nm0443482,nm0653042
tt0000007            nm0179163,nm0183947
tt0000008                      nm0653028
tt0000009  nm0063086,nm0183823,nm1309758
tt0000011                      nm3692297

In [31]:
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,directors
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",7.1,34936,nm0000361
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",5.3,3789,nm0006916
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",6.4,78453,nm0003506
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",5.2,2988,nm0232795
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",5.2,8291,"nm0058045,nm0002045"

In [32]:
print(movies.shape)
movies = pd.merge(movies,principals,left_on='id',right_on='tconst')
print(movies.shape)
movies.head()

(8030, 16)
(7859, 17)

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,nconst
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",7.1,34936,nm0000361,"nm0000323,nm0001141,nm0000262"
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",5.3,3789,nm0006916,"nm0000323,nm0001831,nm0700574"
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",6.4,78453,nm0003506,"nm0000212,nm0413168,nm0000630"
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",5.2,2988,nm0232795,"nm0010915,nm0397109,nm0000482"
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",5.2,8291,"nm0058045,nm0002045","nm0000396,nm0000018,nm0000172"

In [33]:
#split nconst(top 3 listed actors of the movie) into 3 columns

def split_nconst(row):
    """
    splits the contents of column nconst for a given row, returning a list
    the list will allway have three elements
    """
    l = str(movies['nconst'][movies['id']==row['id']].tolist()[0]).split(",")
    if len(l) <3:
        if len(l) == 2:
            l.append('')
        if len(l) == 1:
            l.append('')
            l.append('')
    return l
    
movies['actor1'] = movies.apply(lambda row: split_nconst(row)[0], axis = 1)
movies['actor2'] = movies.apply(lambda row: split_nconst(row)[1], axis = 1)
movies['actor3'] = movies.apply(lambda row: split_nconst(row)[2], axis = 1)

In [34]:
# saving a copy, just in case
pickle.dump(movies,open('movies.pkl',"wb"))

In [35]:
"""
!!! THIS SAVES TIME !!!
"""

movies = pickle.load(open('movies.pkl',"rb"))

In [36]:
# Time to start cleaning this table up
# I'll keep just one of the directors
def one_director(row):
    return str(movies['directors'][movies['id']==row['id']].tolist()[0]).split(",")[0]

movies['directors'] = movies.apply(lambda row: one_director(row), axis = 1)
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,nconst,actor1,actor2,actor3
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",7.1,34936,nm0000361,"nm0000323,nm0001141,nm0000262",nm0000323,nm0001141,nm0000262
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",5.3,3789,nm0006916,"nm0000323,nm0001831,nm0700574",nm0000323,nm0001831,nm0700574
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",6.4,78453,nm0003506,"nm0000212,nm0413168,nm0000630",nm0000212,nm0413168,nm0000630
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",5.2,2988,nm0232795,"nm0010915,nm0397109,nm0000482",nm0010915,nm0397109,nm0000482
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",5.2,8291,nm0058045,"nm0000396,nm0000018,nm0000172",nm0000396,nm0000018,nm0000172

In [37]:
# counting all NaN in df
len(movies) - movies.count()

story             0
budget            0
gross             0
cumulative        0
rating            0
id                0
budget_cy         0
gross_cy          0
cumulative_cy     0
primaryTitle      0
startYear         0
runtimeMinutes    0
genres            1
averageRating     0
numVotes          0
directors         0
nconst            0
actor1            0
actor2            0
actor3            0
dtype: int64

In [38]:
movies.dropna().shape

(7858, 20)

In [39]:
movies.shape

(7859, 20)

In [40]:
movies.dropna(inplace=True)

In [41]:
movies.shape

(7858, 20)

In [42]:

movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,gross_cy,cumulative_cy,primaryTitle,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,nconst,actor1,actor2,actor3
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,USD,USD,Dressed to Kill,1980.0,104,"Crime,Drama,Mystery",7.1,34936,nm0000361,"nm0000323,nm0001141,nm0000262",nm0000323,nm0001141,nm0000262
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,USD,USD,The Island,1980.0,109,"Action,Adventure,Drama",5.3,3789,nm0006916,"nm0000323,nm0001831,nm0700574",nm0000323,nm0001831,nm0700574
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,USD,USD,Kate & Leopold,2001.0,118,"Comedy,Fantasy,Romance",6.4,78453,nm0003506,"nm0000212,nm0413168,nm0000630",nm0000212,nm0413168,nm0000630
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,USD,USD,The Nude Bomb,1980.0,94,"Action,Comedy,Crime",5.2,2988,nm0232795,"nm0010915,nm0397109,nm0000482",nm0010915,nm0397109,nm0000482
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,USD,USD,Saturn 3,1980.0,96,"Adventure,Horror,Sci-Fi",5.2,8291,nm0058045,"nm0000396,nm0000018,nm0000172",nm0000396,nm0000018,nm0000172

In [43]:
# time to drop come useless columns, like nconst (redundant, I have the names), 'primaryTitle' (I won't use it in the model)
# gross an cumulative currency beacause it's always USD
#movies.gross_cy.unique()
#movies.cumulative_cy.unique()

movies.drop(columns=['nconst','primaryTitle', 'gross_cy', 'cumulative_cy'], inplace = True)

In [44]:
# let's one-hot encode genres
# to save time I'll try to use a count vectorizer from NLP class
from sklearn.feature_extraction.text import CountVectorizer
bow_vect = CountVectorizer()

#splitting contents of genre column into list of strings
def split_genre(row):
    return row['genres'].split(',')

movies['genres'] = movies.apply(lambda row: split_genre(row), axis = 1)

#putting it togheter with spaces
def re_blob(row):
    return " ".join(row['genres'])

movies['genres'] = movies.apply(re_blob,axis=1)

movies.head()
#let's use the count vectorizer

,story,budget,gross,cumulative,rating,id,budget_cy,startYear,runtimeMinutes,genres,averageRating,numVotes,directors,actor1,actor2,actor3
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,1980.0,104,Crime Drama Mystery,7.1,34936,nm0000361,nm0000323,nm0001141,nm0000262
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,1980.0,109,Action Adventure Drama,5.3,3789,nm0006916,nm0000323,nm0001831,nm0700574
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,2001.0,118,Comedy Fantasy Romance,6.4,78453,nm0003506,nm0000212,nm0413168,nm0000630
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,1980.0,94,Action Comedy Crime,5.2,2988,nm0232795,nm0010915,nm0397109,nm0000482
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,1980.0,96,Adventure Horror Sci-Fi,5.2,8291,nm0058045,nm0000396,nm0000018,nm0000172

In [45]:
X = bow_vect.fit_transform(movies['genres']).toarray()
as_df = pd.DataFrame(X,columns=bow_vect.get_feature_names())
as_df.shape

(7858, 23)

In [46]:
movies.shape

(7858, 16)

In [47]:
#adding id to as_df (it has the same ordering so it's ok)
as_df['id']=movies['id']
as_df.head()

,action,adventure,animation,biography,comedy,crime,documentary,drama,family,fantasy,...,musical,mystery,news,romance,sci,sport,thriller,war,western,id
0,0,0,0,0,0,1,0,1,0,0,...,0,1,0,0,0,0,0,0,0,tt0080661
1,1,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,tt0080934
2,0,0,0,0,1,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,tt0035423
3,1,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,tt0081249
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,tt0079285

In [48]:
#merging both
movies = pd.merge(movies,as_df,left_on='id',right_on='id')
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,startYear,runtimeMinutes,genres,...,music,musical,mystery,news,romance,sci,sport,thriller,war,western
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,1980.0,104,Crime Drama Mystery,...,0,0,1,0,0,0,0,0,0,0
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,1980.0,109,Action Adventure Drama,...,0,0,0,0,0,0,0,0,0,0
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,2001.0,118,Comedy Fantasy Romance,...,0,0,0,0,1,0,0,0,0,0
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,1980.0,94,Action Comedy Crime,...,0,0,0,0,0,0,0,0,0,0
4,Two lovers stationed at a remote base in the a...,10000000,9000000,9000000,R,tt0079285,GBP,1980.0,96,Adventure Horror Sci-Fi,...,0,0,0,0,0,1,0,0,0,0

In [49]:
# genres is redundant now
movies.drop(columns=['genres'],inplace=True)

In [50]:
# time to drop all movies with budget not in USD
print(movies.shape)
movies = movies[movies['budget_cy']=='USD']
print(movies.shape)
movies.head()

(7857, 38)
(7110, 38)

,story,budget,gross,cumulative,rating,id,budget_cy,startYear,runtimeMinutes,averageRating,...,music,musical,mystery,news,romance,sci,sport,thriller,war,western
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,1980.0,104,7.1,...,0,0,1,0,0,0,0,0,0,0
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,1980.0,109,5.3,...,0,0,0,0,0,0,0,0,0,0
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,2001.0,118,6.4,...,0,0,0,0,1,0,0,0,0,0
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,1980.0,94,5.2,...,0,0,0,0,0,0,0,0,0,0
5,"In Victorian London, Dr. Frederick Treves with...",5000000,26010864,26021332,PG,tt0080678,USD,1980.0,124,8.1,...,0,0,0,0,0,0,0,0,0,0

In [51]:
# time to create ROI column

movies['ROI'] = (movies['cumulative'] - movies['budget']) / movies['budget']
movies.head()

,story,budget,gross,cumulative,rating,id,budget_cy,startYear,runtimeMinutes,averageRating,...,musical,mystery,news,romance,sci,sport,thriller,war,western,ROI
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,USD,1980.0,104,7.1,...,0,1,0,0,0,0,0,0,0,3.907538
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,USD,1980.0,109,5.3,...,0,0,0,0,0,0,0,0,0,-0.285599
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,USD,2001.0,118,6.4,...,0,0,0,1,0,0,0,0,0,0.583730
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,USD,1980.0,94,5.2,...,0,0,0,0,0,0,0,0,0,-0.022531
5,"In Victorian London, Dr. Frederick Treves with...",5000000,26010864,26021332,PG,tt0080678,USD,1980.0,124,8.1,...,0,0,0,0,0,0,0,0,0,4.204266

In [52]:
#everything is in USD, I don't need budget_cy anymore
movies.drop(columns=['budget_cy'],inplace=True)

In [53]:
# Creating target variable, result
# Result will be 'loss' if movie has a ROI of -20% or lower, 'even' if ROI is between ]-20%,20%[ and 
# 'hit' if movie has an ROI of over 20%
# I may revise this to only have two labels, loss and profit

movies.loc[movies['ROI'] <= -0.2, 'result'] = 'loss'
movies.loc[movies['ROI'] >= 0.2, 'result'] = 'profit'
movies.loc[(movies['ROI'] > -0.2)&(movies['ROI'] < 0.2), 'result'] = 'even'

In [55]:
# now I will hot one encode rating
movies = pd.merge(left = movies, right = pd.get_dummies(movies['rating'],prefix='rating'), left_index = True, right_index = True)
movies.head()

,story,budget,gross,cumulative,rating,id,startYear,runtimeMinutes,averageRating,numVotes,...,rating_Not Rated,rating_PG,rating_PG-13,rating_R,rating_TV-14,rating_TV-G,rating_TV-MA,rating_TV-PG,rating_Unrated,rating_X
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,1980.0,104,7.1,34936,...,0,0,0,1,0,0,0,0,0,0
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,1980.0,109,5.3,3789,...,0,0,0,1,0,0,0,0,0,0
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,2001.0,118,6.4,78453,...,0,0,1,0,0,0,0,0,0,0
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,1980.0,94,5.2,2988,...,0,1,0,0,0,0,0,0,0,0
5,"In Victorian London, Dr. Frederick Treves with...",5000000,26010864,26021332,PG,tt0080678,1980.0,124,8.1,217572,...,0,1,0,0,0,0,0,0,0,0

In [56]:
movies.dtypes

story                object
budget                int64
gross                 int64
cumulative            int64
rating               object
id                   object
startYear           float64
runtimeMinutes       object
averageRating       float64
numVotes              int64
directors            object
actor1               object
actor2               object
actor3               object
action                int64
adventure             int64
animation             int64
biography             int64
comedy                int64
crime                 int64
documentary           int64
drama                 int64
family                int64
fantasy               int64
fi                    int64
history               int64
horror                int64
music                 int64
musical               int64
mystery               int64
news                  int64
romance               int64
sci                   int64
sport                 int64
thriller              int64
war                   int64
western               int64
ROI                 float64
result               object
rating_Approved       uint8
rating_G              uint8
rating_NC-17          uint8
rating_Not Rated      uint8
rating_PG             uint8
rating_PG-13          uint8
rating_R              uint8
rating_TV-14          uint8
rating_TV-G           uint8
rating_TV-MA          uint8
rating_TV-PG          uint8
rating_Unrated        uint8
rating_X              uint8
dtype: object

In [57]:
movies[['sci','fi']].tail(20)

      sci  fi
7836    0   0
7837    0   0
7838    0   0
7839    0   0
7840    0   0
7841    0   0
7842    0   0
7843    1   1
7844    0   0
7845    0   0
7846    0   0
7847    0   0
7848    0   0
7849    0   0
7851    0   0
7852    0   0
7853    0   0
7854    0   0
7855    0   0
7856    0   0

In [58]:
#sci-fi was splitted in two, I have to solve this
#movies.drop(columns='fi',inplace=True)
movies.rename(columns={'sci':'sci-fi'},inplace = True)
movies.dtypes

story                object
budget                int64
gross                 int64
cumulative            int64
rating               object
id                   object
startYear           float64
runtimeMinutes       object
averageRating       float64
numVotes              int64
directors            object
actor1               object
actor2               object
actor3               object
action                int64
adventure             int64
animation             int64
biography             int64
comedy                int64
crime                 int64
documentary           int64
drama                 int64
family                int64
fantasy               int64
fi                    int64
history               int64
horror                int64
music                 int64
musical               int64
mystery               int64
news                  int64
romance               int64
sci-fi                int64
sport                 int64
thriller              int64
war                   int64
western               int64
ROI                 float64
result               object
rating_Approved       uint8
rating_G              uint8
rating_NC-17          uint8
rating_Not Rated      uint8
rating_PG             uint8
rating_PG-13          uint8
rating_R              uint8
rating_TV-14          uint8
rating_TV-G           uint8
rating_TV-MA          uint8
rating_TV-PG          uint8
rating_Unrated        uint8
rating_X              uint8
dtype: object

In [59]:
# table with the average rating of the movies a actor is in, by column
actors1 = pd.pivot_table(movies, values = 'averageRating', index = 'actor1', aggfunc = 'mean')
actors2 = pd.pivot_table(movies, values = 'averageRating', index = 'actor2', aggfunc = 'mean')
actors3 = pd.pivot_table(movies, values = 'averageRating', index = 'actor3', aggfunc = 'mean')

In [60]:
# now for all the movies the actor is credited in any of the top three spots (column actor1,2 or 3)
actors_rating = pd.concat([actors1, actors2, actors3]).groupby(level=0).mean()
actors_rating.head()

           averageRating
                6.827393
nm0000002       6.412500
nm0000004       6.750000
nm0000008       5.961111
nm0000018       6.650000

In [61]:
actors_rating.reset_index(inplace=True)
actors_rating.head()

       index  averageRating
0                  6.827393
1  nm0000002       6.412500
2  nm0000004       6.750000
3  nm0000008       5.961111
4  nm0000018       6.650000

In [62]:
# sometimes, a movie doesn't have 1, 2 or 3 actors listed, so I have an entry in my actors 
# rating table without index (actor id)
# I have to drop this
actors_rating.drop(actors_rating.index[0],inplace=True)
actors_rating.head()

       index  averageRating
1  nm0000002       6.412500
2  nm0000004       6.750000
3  nm0000008       5.961111
4  nm0000018       6.650000
5  nm0000024       6.875000

In [64]:
movies.rename(columns={'averageRating': 'avgRt'}, inplace = True)

In [65]:
# I must use a left join merge to get this data into a new column in the movies table
# I have to do it three times, for each of the top three actors
# I'll then calculate the average rating across the three new columns and save it in a column
# called star_rating
print(movies.shape)
movies = pd.merge(left = movies, right = actors_rating, left_on = 'actor1', right_on = 'index', how = 'left', suffixes = '_a')
movies.drop(columns=['index'],inplace=True)
movies = pd.merge(left = movies, right = actors_rating, left_on = 'actor2', right_on = 'index', how = 'left', suffixes = '_b')
movies.drop(columns=['index'],inplace=True)
movies = pd.merge(left = movies, right = actors_rating, left_on = 'actor3', right_on = 'index', how = 'left', suffixes = '_c')
movies.drop(columns=['index'],inplace=True)
print(movies.shape)
movies.head()

(7110, 52)
(7110, 55)

,story,budget,gross,cumulative,rating,id,startYear,runtimeMinutes,avgRt,numVotes,...,rating_R,rating_TV-14,rating_TV-G,rating_TV-MA,rating_TV-PG,rating_Unrated,rating_X,averageRating_,averageRatingb,averageRating
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,1980.0,104,7.1,34936,...,1,0,0,0,0,0,0,6.607033,7.100000,6.040
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,1980.0,109,5.3,3789,...,1,0,0,0,0,0,0,6.607033,6.225000,5.300
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,2001.0,118,6.4,78453,...,0,0,0,0,0,0,0,6.306667,6.927179,6.325
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,1980.0,94,5.2,2988,...,0,0,0,0,0,0,0,5.200000,5.200000,5.200
4,"In Victorian London, Dr. Frederick Treves with...",5000000,26010864,26021332,PG,tt0080678,1980.0,124,8.1,217572,...,0,0,0,0,0,0,0,6.618875,6.237778,6.400

In [66]:
movies[['actor1','actor2','actor3','averageRating_','averageRatingb','averageRating']].head()

,actor1,actor2,actor3,averageRating_,averageRatingb,averageRating
0,nm0000323,nm0001141,nm0000262,6.607033,7.100000,6.040
1,nm0000323,nm0001831,nm0700574,6.607033,6.225000,5.300
2,nm0000212,nm0413168,nm0000630,6.306667,6.927179,6.325
3,nm0010915,nm0397109,nm0000482,5.200000,5.200000,5.200
4,nm0000164,nm0000457,nm0000843,6.618875,6.237778,6.400

In [75]:
def mean_rt(row):
    '''
    takes a row and returns the average of 'averageRating_','averageRatingb','averageRating'
    '''
    i=0
    s=0
    if pd.isna(row['averageRating_']) == False:
        i+=1
        s+=row['averageRating_']
    if pd.isna(row['averageRatingb']) == False:
        i+=1
        s+=row['averageRatingb']
    if pd.isna(row['averageRating']) == False:
        i+=1
        s+=row['averageRating']
    if i == 0:
        return ''
    else:
        return s/i

movies['starsIMDB'] = movies.apply(lambda row: mean_rt(row), axis = 1)

In [79]:
movies.drop(columns=['averageRating_','averageRatingb','averageRating'],inplace=True)
movies.head()

,story,budget,gross,cumulative,rating,id,startYear,runtimeMinutes,avgRt,numVotes,...,rating_PG,rating_PG-13,rating_R,rating_TV-14,rating_TV-G,rating_TV-MA,rating_TV-PG,rating_Unrated,rating_X,starsIMDB
0,"While taking a shower, Kate Miller, a middle-a...",6500000,31899000,31899000,R,tt0080661,1980.0,104,7.1,34936,...,0,0,1,0,0,0,0,0,0,6.582344
1,"In New York City, journalist Blair Maynard con...",22000000,15716828,15716828,R,tt0080934,1980.0,109,5.3,3789,...,0,0,1,0,0,0,0,0,0,6.044011
2,Kate and her actor brother live in N.Y. in the...,48000000,47121859,76019048,PG-13,tt0035423,2001.0,118,6.4,78453,...,0,1,0,0,0,0,0,0,0,6.519615
3,An unknown terrorist has developed a new type ...,15000000,14662035,14662035,PG,tt0081249,1980.0,94,5.2,2988,...,1,0,0,0,0,0,0,0,0,5.200000
4,"In Victorian London, Dr. Frederick Treves with...",5000000,26010864,26021332,PG,tt0080678,1980.0,124,8.1,217572,...,1,0,0,0,0,0,0,0,0,6.418884

# now I need the director average IMDB score
directors = pd.pivot_table(movies, values = 'averageRating', index = 'actor1', aggfunc = 'mean')